// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: task-interface.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values map[string]string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Descriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Descriptor) Reset() {
	*x = Descriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Descriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Descriptor) ProtoMessage() {}

func (x *Descriptor) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Descriptor.ProtoReflect.Descriptor instead.
func (*Descriptor) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{1}
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2}
}

type Descriptor_Goal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Short   string   `protobuf:"bytes,2,opt,name=short,proto3" json:"short,omitempty"`
	Aliases []string `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
}

func (x *Descriptor_Goal) Reset() {
	*x = Descriptor_Goal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Descriptor_Goal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Descriptor_Goal) ProtoMessage() {}

func (x *Descriptor_Goal) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Descriptor_Goal.ProtoReflect.Descriptor instead.
func (*Descriptor_Goal) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Descriptor_Goal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Descriptor_Goal) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *Descriptor_Goal) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type Descriptor_Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Short    string   `protobuf:"bytes,3,opt,name=short,proto3" json:"short,omitempty"`
	Requires []string `protobuf:"bytes,4,rep,name=requires,proto3" json:"requires,omitempty"`
}

func (x *Descriptor_Task) Reset() {
	*x = Descriptor_Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Descriptor_Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Descriptor_Task) ProtoMessage() {}

func (x *Descriptor_Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Descriptor_Task.ProtoReflect.Descriptor instead.
func (*Descriptor_Task) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Descriptor_Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Descriptor_Task) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *Descriptor_Task) GetRequires() []string {
	if x != nil {
		return x.Requires
	}
	return nil
}

type Task_Implements struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task_Implements) Reset() {
	*x = Task_Implements{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Implements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Implements) ProtoMessage() {}

func (x *Task_Implements) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Implements.ProtoReflect.Descriptor instead.
func (*Task_Implements) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 0}
}

type Task_Goal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task_Goal) Reset() {
	*x = Task_Goal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Goal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Goal) ProtoMessage() {}

func (x *Task_Goal) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Goal.ProtoReflect.Descriptor instead.
func (*Task_Goal) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 1}
}

type Task_Ref struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StateId string `protobuf:"bytes,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
}

func (x *Task_Ref) Reset() {
	*x = Task_Ref{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Ref) ProtoMessage() {}

func (x *Task_Ref) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Ref.ProtoReflect.Descriptor instead.
func (*Task_Ref) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Task_Ref) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task_Ref) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

type Task_Prepare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task_Prepare) Reset() {
	*x = Task_Prepare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Prepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Prepare) ProtoMessage() {}

func (x *Task_Prepare) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Prepare.ProtoReflect.Descriptor instead.
func (*Task_Prepare) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 3}
}

type Task_Cancel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task_Cancel) Reset() {
	*x = Task_Cancel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Cancel) ProtoMessage() {}

func (x *Task_Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Cancel.ProtoReflect.Descriptor instead.
func (*Task_Cancel) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 4}
}

type Task_Complete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task_Complete) Reset() {
	*x = Task_Complete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Complete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Complete) ProtoMessage() {}

func (x *Task_Complete) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Complete.ProtoReflect.Descriptor instead.
func (*Task_Complete) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 5}
}

type Task_Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task_Operation) Reset() {
	*x = Task_Operation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Operation) ProtoMessage() {}

func (x *Task_Operation) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Operation.ProtoReflect.Descriptor instead.
func (*Task_Operation) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 6}
}

type Task_SubStage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task_SubStage) Reset() {
	*x = Task_SubStage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_SubStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_SubStage) ProtoMessage() {}

func (x *Task_SubStage) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_SubStage.ProtoReflect.Descriptor instead.
func (*Task_SubStage) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 7}
}

type Task_Implements_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*Descriptor_Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *Task_Implements_Response) Reset() {
	*x = Task_Implements_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Implements_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Implements_Response) ProtoMessage() {}

func (x *Task_Implements_Response) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Implements_Response.ProtoReflect.Descriptor instead.
func (*Task_Implements_Response) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Task_Implements_Response) GetTasks() []*Descriptor_Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Task_Implements_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task_Implements_Request) Reset() {
	*x = Task_Implements_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Implements_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Implements_Request) ProtoMessage() {}

func (x *Task_Implements_Request) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Implements_Request.ProtoReflect.Descriptor instead.
func (*Task_Implements_Request) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 0, 1}
}

type Task_Goal_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Definition *Descriptor_Goal `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
}

func (x *Task_Goal_Response) Reset() {
	*x = Task_Goal_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Goal_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Goal_Response) ProtoMessage() {}

func (x *Task_Goal_Response) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Goal_Response.ProtoReflect.Descriptor instead.
func (*Task_Goal_Response) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 1, 0}
}

func (x *Task_Goal_Response) GetDefinition() *Descriptor_Goal {
	if x != nil {
		return x.Definition
	}
	return nil
}

type Task_Goal_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Task_Goal_Request) Reset() {
	*x = Task_Goal_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Goal_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Goal_Request) ProtoMessage() {}

func (x *Task_Goal_Request) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Goal_Request.ProtoReflect.Descriptor instead.
func (*Task_Goal_Request) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 1, 1}
}

func (x *Task_Goal_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Task_Prepare_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GlobalConfig *Config `protobuf:"bytes,2,opt,name=global_config,json=globalConfig,proto3" json:"global_config,omitempty"`
}

func (x *Task_Prepare_Request) Reset() {
	*x = Task_Prepare_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Prepare_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Prepare_Request) ProtoMessage() {}

func (x *Task_Prepare_Request) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Prepare_Request.ProtoReflect.Descriptor instead.
func (*Task_Prepare_Request) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 3, 0}
}

func (x *Task_Prepare_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task_Prepare_Request) GetGlobalConfig() *Config {
	if x != nil {
		return x.GlobalConfig
	}
	return nil
}

type Task_Prepare_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task    *Task_Ref         `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Storage map[string]string `protobuf:"bytes,2,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Task_Prepare_Response) Reset() {
	*x = Task_Prepare_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Prepare_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Prepare_Response) ProtoMessage() {}

func (x *Task_Prepare_Response) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Prepare_Response.ProtoReflect.Descriptor instead.
func (*Task_Prepare_Response) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 3, 1}
}

func (x *Task_Prepare_Response) GetTask() *Task_Ref {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *Task_Prepare_Response) GetStorage() map[string]string {
	if x != nil {
		return x.Storage
	}
	return nil
}

type Task_Cancel_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task    *Task_Ref         `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Storage map[string]string `protobuf:"bytes,2,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Task_Cancel_Request) Reset() {
	*x = Task_Cancel_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Cancel_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Cancel_Request) ProtoMessage() {}

func (x *Task_Cancel_Request) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Cancel_Request.ProtoReflect.Descriptor instead.
func (*Task_Cancel_Request) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 4, 0}
}

func (x *Task_Cancel_Request) GetTask() *Task_Ref {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *Task_Cancel_Request) GetStorage() map[string]string {
	if x != nil {
		return x.Storage
	}
	return nil
}

type Task_Cancel_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task_Cancel_Response) Reset() {
	*x = Task_Cancel_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Cancel_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Cancel_Response) ProtoMessage() {}

func (x *Task_Cancel_Response) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Cancel_Response.ProtoReflect.Descriptor instead.
func (*Task_Cancel_Response) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 4, 1}
}

type Task_Complete_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task    *Task_Ref         `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Storage map[string]string `protobuf:"bytes,2,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Task_Complete_Request) Reset() {
	*x = Task_Complete_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Complete_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Complete_Request) ProtoMessage() {}

func (x *Task_Complete_Request) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Complete_Request.ProtoReflect.Descriptor instead.
func (*Task_Complete_Request) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 5, 0}
}

func (x *Task_Complete_Request) GetTask() *Task_Ref {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *Task_Complete_Request) GetStorage() map[string]string {
	if x != nil {
		return x.Storage
	}
	return nil
}

type Task_Complete_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Task_Complete_Response) Reset() {
	*x = Task_Complete_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Complete_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Complete_Response) ProtoMessage() {}

func (x *Task_Complete_Response) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Complete_Response.ProtoReflect.Descriptor instead.
func (*Task_Complete_Response) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 5, 1}
}

type Task_Operation_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task    *Task_Ref         `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Storage map[string]string `protobuf:"bytes,2,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Task_Operation_Request) Reset() {
	*x = Task_Operation_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Operation_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Operation_Request) ProtoMessage() {}

func (x *Task_Operation_Request) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Operation_Request.ProtoReflect.Descriptor instead.
func (*Task_Operation_Request) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 6, 0}
}

func (x *Task_Operation_Request) GetTask() *Task_Ref {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *Task_Operation_Request) GetStorage() map[string]string {
	if x != nil {
		return x.Storage
	}
	return nil
}

type Task_Operation_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageUpdate map[string]string `protobuf:"bytes,2,rep,name=storage_update,json=storageUpdate,proto3" json:"storage_update,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Task_Operation_Response) Reset() {
	*x = Task_Operation_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_Operation_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_Operation_Response) ProtoMessage() {}

func (x *Task_Operation_Response) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_Operation_Response.ProtoReflect.Descriptor instead.
func (*Task_Operation_Response) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 6, 1}
}

func (x *Task_Operation_Response) GetStorageUpdate() map[string]string {
	if x != nil {
		return x.StorageUpdate
	}
	return nil
}

type Task_SubStage_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProvidedOrders []int32 `protobuf:"varint,1,rep,packed,name=provided_orders,json=providedOrders,proto3" json:"provided_orders,omitempty"`
}

func (x *Task_SubStage_Response) Reset() {
	*x = Task_SubStage_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_SubStage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_SubStage_Response) ProtoMessage() {}

func (x *Task_SubStage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_SubStage_Response.ProtoReflect.Descriptor instead.
func (*Task_SubStage_Response) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 7, 0}
}

func (x *Task_SubStage_Response) GetProvidedOrders() []int32 {
	if x != nil {
		return x.ProvidedOrders
	}
	return nil
}

type Task_SubStage_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *Task_Operation_Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	SubStage int32                   `protobuf:"varint,2,opt,name=sub_stage,json=subStage,proto3" json:"sub_stage,omitempty"`
}

func (x *Task_SubStage_Request) Reset() {
	*x = Task_SubStage_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_interface_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task_SubStage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_SubStage_Request) ProtoMessage() {}

func (x *Task_SubStage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_task_interface_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_SubStage_Request.ProtoReflect.Descriptor instead.
func (*Task_SubStage_Request) Descriptor() ([]byte, []int) {
	return file_task_interface_proto_rawDescGZIP(), []int{2, 7, 1}
}

func (x *Task_SubStage_Request) GetRequest() *Task_Operation_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Task_SubStage_Request) GetSubStage() int32 {
	if x != nil {
		return x.SubStage
	}
	return 0
}

var File_task_interface_proto protoreflect.FileDescriptor

var file_task_interface_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x22, 0x7d, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x38,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0xa6, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x1a, 0x4a, 0x0a, 0x04, 0x47, 0x6f, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x1a, 0x4c,
	0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x22, 0x86, 0x0c, 0x0a,
	0x04, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x58, 0x0a, 0x0a, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x1a, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74,
	0x61, 0x73, 0x6b, 0x73, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x70, 0x0a, 0x04, 0x47, 0x6f, 0x61, 0x6c, 0x1a, 0x49, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f,
	0x72, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x52, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x1a, 0x34, 0x0a, 0x03, 0x52, 0x65, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x1a, 0xa4, 0x02, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x1a, 0x58, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x7a, 0x65, 0x64, 0x70,
	0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x0c, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0xbe, 0x01,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x61,
	0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52, 0x65, 0x66,
	0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x4a, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x50, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x1a, 0x3a, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0xd2,
	0x01, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x1a, 0xbb, 0x01, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52, 0x65, 0x66, 0x52, 0x04, 0x74, 0x61, 0x73,
	0x6b, 0x12, 0x48, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x3a, 0x0a, 0x0c, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x1a, 0xd6, 0x01, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x1a, 0xbd, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04,
	0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x7a, 0x65, 0x64,
	0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52,
	0x65, 0x66, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x4a, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x7a, 0x65, 0x64, 0x70,
	0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x1a, 0x3a, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0xfc, 0x02, 0x0a,
	0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0xbe, 0x01, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52, 0x65, 0x66, 0x52, 0x04, 0x74, 0x61,
	0x73, 0x6b, 0x12, 0x4b, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a,
	0x3a, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0xad, 0x01, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x0e, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x38, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x40, 0x0a, 0x12, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0xa7, 0x01, 0x0a, 0x08,
	0x53, 0x75, 0x62, 0x53, 0x74, 0x61, 0x67, 0x65, 0x1a, 0x33, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x64,
	0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0e, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x66, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x7a, 0x65, 0x64, 0x70,
	0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x75, 0x62,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x32, 0xfe, 0x08, 0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5d, 0x0a, 0x0a, 0x49, 0x6d, 0x70, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x7a,
	0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x2e, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x04, 0x47, 0x6f, 0x61, 0x6c, 0x12, 0x1f,
	0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x22,
	0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x06, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x12, 0x21, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x08,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x24, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x7a, 0x65,
	0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x42,
	0x65, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52, 0x65, 0x66, 0x1a, 0x24, 0x2e, 0x7a,
	0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x2e, 0x53, 0x75, 0x62, 0x53, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x42,
	0x65, 0x67, 0x69, 0x6e, 0x12, 0x23, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x53, 0x75, 0x62, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x7a, 0x65, 0x64, 0x70,
	0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x75, 0x6e,
	0x12, 0x16, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52, 0x65, 0x66, 0x1a, 0x24, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x53, 0x75, 0x62,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x5a, 0x0a, 0x0a, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x12, 0x23,
	0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x2e, 0x53, 0x75, 0x62, 0x53, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0a,
	0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x16, 0x2e, 0x7a, 0x65, 0x64,
	0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x52,
	0x65, 0x66, 0x1a, 0x24, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x53, 0x75, 0x62, 0x53, 0x74, 0x61, 0x67, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0a, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x23, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x53, 0x75, 0x62,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x0d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x12, 0x24, 0x2e, 0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x7a, 0x65, 0x64, 0x70, 0x6d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_task_interface_proto_rawDescOnce sync.Once
	file_task_interface_proto_rawDescData = file_task_interface_proto_rawDesc
)

func file_task_interface_proto_rawDescGZIP() []byte {
	file_task_interface_proto_rawDescOnce.Do(func() {
		file_task_interface_proto_rawDescData = protoimpl.X.CompressGZIP(file_task_interface_proto_rawDescData)
	})
	return file_task_interface_proto_rawDescData
}

var file_task_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_task_interface_proto_goTypes = []interface{}{
	(*Config)(nil),                   // 0: zedpm.plugin.Config
	(*Descriptor)(nil),               // 1: zedpm.plugin.Descriptor
	(*Task)(nil),                     // 2: zedpm.plugin.Task
	nil,                              // 3: zedpm.plugin.Config.ValuesEntry
	(*Descriptor_Goal)(nil),          // 4: zedpm.plugin.Descriptor.Goal
	(*Descriptor_Task)(nil),          // 5: zedpm.plugin.Descriptor.Task
	(*Task_Implements)(nil),          // 6: zedpm.plugin.Task.Implements
	(*Task_Goal)(nil),                // 7: zedpm.plugin.Task.Goal
	(*Task_Ref)(nil),                 // 8: zedpm.plugin.Task.Ref
	(*Task_Prepare)(nil),             // 9: zedpm.plugin.Task.Prepare
	(*Task_Cancel)(nil),              // 10: zedpm.plugin.Task.Cancel
	(*Task_Complete)(nil),            // 11: zedpm.plugin.Task.Complete
	(*Task_Operation)(nil),           // 12: zedpm.plugin.Task.Operation
	(*Task_SubStage)(nil),            // 13: zedpm.plugin.Task.SubStage
	(*Task_Implements_Response)(nil), // 14: zedpm.plugin.Task.Implements.Response
	(*Task_Implements_Request)(nil),  // 15: zedpm.plugin.Task.Implements.Request
	(*Task_Goal_Response)(nil),       // 16: zedpm.plugin.Task.Goal.Response
	(*Task_Goal_Request)(nil),        // 17: zedpm.plugin.Task.Goal.Request
	(*Task_Prepare_Request)(nil),     // 18: zedpm.plugin.Task.Prepare.Request
	(*Task_Prepare_Response)(nil),    // 19: zedpm.plugin.Task.Prepare.Response
	nil,                              // 20: zedpm.plugin.Task.Prepare.Response.StorageEntry
	(*Task_Cancel_Request)(nil),      // 21: zedpm.plugin.Task.Cancel.Request
	(*Task_Cancel_Response)(nil),     // 22: zedpm.plugin.Task.Cancel.Response
	nil,                              // 23: zedpm.plugin.Task.Cancel.Request.StorageEntry
	(*Task_Complete_Request)(nil),    // 24: zedpm.plugin.Task.Complete.Request
	(*Task_Complete_Response)(nil),   // 25: zedpm.plugin.Task.Complete.Response
	nil,                              // 26: zedpm.plugin.Task.Complete.Request.StorageEntry
	(*Task_Operation_Request)(nil),   // 27: zedpm.plugin.Task.Operation.Request
	(*Task_Operation_Response)(nil),  // 28: zedpm.plugin.Task.Operation.Response
	nil,                              // 29: zedpm.plugin.Task.Operation.Request.StorageEntry
	nil,                              // 30: zedpm.plugin.Task.Operation.Response.StorageUpdateEntry
	(*Task_SubStage_Response)(nil),   // 31: zedpm.plugin.Task.SubStage.Response
	(*Task_SubStage_Request)(nil),    // 32: zedpm.plugin.Task.SubStage.Request
}
var file_task_interface_proto_depIdxs = []int32{
	3,  // 0: zedpm.plugin.Config.values:type_name -> zedpm.plugin.Config.ValuesEntry
	5,  // 1: zedpm.plugin.Task.Implements.Response.tasks:type_name -> zedpm.plugin.Descriptor.Task
	4,  // 2: zedpm.plugin.Task.Goal.Response.definition:type_name -> zedpm.plugin.Descriptor.Goal
	0,  // 3: zedpm.plugin.Task.Prepare.Request.global_config:type_name -> zedpm.plugin.Config
	8,  // 4: zedpm.plugin.Task.Prepare.Response.task:type_name -> zedpm.plugin.Task.Ref
	20, // 5: zedpm.plugin.Task.Prepare.Response.storage:type_name -> zedpm.plugin.Task.Prepare.Response.StorageEntry
	8,  // 6: zedpm.plugin.Task.Cancel.Request.task:type_name -> zedpm.plugin.Task.Ref
	23, // 7: zedpm.plugin.Task.Cancel.Request.storage:type_name -> zedpm.plugin.Task.Cancel.Request.StorageEntry
	8,  // 8: zedpm.plugin.Task.Complete.Request.task:type_name -> zedpm.plugin.Task.Ref
	26, // 9: zedpm.plugin.Task.Complete.Request.storage:type_name -> zedpm.plugin.Task.Complete.Request.StorageEntry
	8,  // 10: zedpm.plugin.Task.Operation.Request.task:type_name -> zedpm.plugin.Task.Ref
	29, // 11: zedpm.plugin.Task.Operation.Request.storage:type_name -> zedpm.plugin.Task.Operation.Request.StorageEntry
	30, // 12: zedpm.plugin.Task.Operation.Response.storage_update:type_name -> zedpm.plugin.Task.Operation.Response.StorageUpdateEntry
	27, // 13: zedpm.plugin.Task.SubStage.Request.request:type_name -> zedpm.plugin.Task.Operation.Request
	15, // 14: zedpm.plugin.TaskExecution.Implements:input_type -> zedpm.plugin.Task.Implements.Request
	17, // 15: zedpm.plugin.TaskExecution.Goal:input_type -> zedpm.plugin.Task.Goal.Request
	18, // 16: zedpm.plugin.TaskExecution.Prepare:input_type -> zedpm.plugin.Task.Prepare.Request
	21, // 17: zedpm.plugin.TaskExecution.Cancel:input_type -> zedpm.plugin.Task.Cancel.Request
	24, // 18: zedpm.plugin.TaskExecution.Complete:input_type -> zedpm.plugin.Task.Complete.Request
	27, // 19: zedpm.plugin.TaskExecution.ExecuteCheck:input_type -> zedpm.plugin.Task.Operation.Request
	8,  // 20: zedpm.plugin.TaskExecution.PrepareBegin:input_type -> zedpm.plugin.Task.Ref
	32, // 21: zedpm.plugin.TaskExecution.ExecuteBegin:input_type -> zedpm.plugin.Task.SubStage.Request
	8,  // 22: zedpm.plugin.TaskExecution.PrepareRun:input_type -> zedpm.plugin.Task.Ref
	32, // 23: zedpm.plugin.TaskExecution.ExecuteRun:input_type -> zedpm.plugin.Task.SubStage.Request
	8,  // 24: zedpm.plugin.TaskExecution.PrepareEnd:input_type -> zedpm.plugin.Task.Ref
	32, // 25: zedpm.plugin.TaskExecution.ExecuteEnd:input_type -> zedpm.plugin.Task.SubStage.Request
	27, // 26: zedpm.plugin.TaskExecution.ExecuteFinish:input_type -> zedpm.plugin.Task.Operation.Request
	14, // 27: zedpm.plugin.TaskExecution.Implements:output_type -> zedpm.plugin.Task.Implements.Response
	16, // 28: zedpm.plugin.TaskExecution.Goal:output_type -> zedpm.plugin.Task.Goal.Response
	19, // 29: zedpm.plugin.TaskExecution.Prepare:output_type -> zedpm.plugin.Task.Prepare.Response
	22, // 30: zedpm.plugin.TaskExecution.Cancel:output_type -> zedpm.plugin.Task.Cancel.Response
	25, // 31: zedpm.plugin.TaskExecution.Complete:output_type -> zedpm.plugin.Task.Complete.Response
	28, // 32: zedpm.plugin.TaskExecution.ExecuteCheck:output_type -> zedpm.plugin.Task.Operation.Response
	31, // 33: zedpm.plugin.TaskExecution.PrepareBegin:output_type -> zedpm.plugin.Task.SubStage.Response
	28, // 34: zedpm.plugin.TaskExecution.ExecuteBegin:output_type -> zedpm.plugin.Task.Operation.Response
	31, // 35: zedpm.plugin.TaskExecution.PrepareRun:output_type -> zedpm.plugin.Task.SubStage.Response
	28, // 36: zedpm.plugin.TaskExecution.ExecuteRun:output_type -> zedpm.plugin.Task.Operation.Response
	31, // 37: zedpm.plugin.TaskExecution.PrepareEnd:output_type -> zedpm.plugin.Task.SubStage.Response
	28, // 38: zedpm.plugin.TaskExecution.ExecuteEnd:output_type -> zedpm.plugin.Task.Operation.Response
	28, // 39: zedpm.plugin.TaskExecution.ExecuteFinish:output_type -> zedpm.plugin.Task.Operation.Response
	27, // [27:40] is the sub-list for method output_type
	14, // [14:27] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_task_interface_proto_init() }
func file_task_interface_proto_init() {
	if File_task_interface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_task_interface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Descriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Descriptor_Goal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Descriptor_Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Implements); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Goal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Ref); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Prepare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Cancel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Complete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Operation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_SubStage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Implements_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Implements_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Goal_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Goal_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Prepare_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Prepare_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Cancel_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Cancel_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Complete_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Complete_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Operation_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_Operation_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_SubStage_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_task_interface_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task_SubStage_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_task_interface_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_interface_proto_goTypes,
		DependencyIndexes: file_task_interface_proto_depIdxs,
		MessageInfos:      file_task_interface_proto_msgTypes,
	}.Build()
	File_task_interface_proto = out.File
	file_task_interface_proto_rawDesc = nil
	file_task_interface_proto_goTypes = nil
	file_task_interface_proto_depIdxs = nil
}
